version: "3"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
      PORT: 4000
    ports:
      - 4000:4000